### ISSUE TITLE
Return owner address in public resolver if ETH address isn't set

### ISSUE THREAD

**Issue by 0xc0de4c0ffee** [ensdomains/ens-contracts#107]
Public resolver should return address of node owner from ENS contract if it's not already set.
That'll save users from one tx/gas, and users can change their addr anytime.

https://github.com/ensdomains/ens-contracts/blob/f479f41b2fdab6e2ae82242ffb87ae42dcdf271d/contracts/resolvers/profiles/AddrResolver.sol#L28-L34

I'd send a PR but `ENS` isn't available in resolver base && I don't want to make a mess around. :pray:
```
     function addr(bytes32 node) virtual override public view returns (address payable) {
        bytes memory a = _addresses[node][COIN_TYPE_ETH];
        if(a.length == 0) {
            return payable(ENS.owner(node));
        }
        return bytesToAddress(a);
    }
```

**Comment by jefflau** [comment]
With .eth names you have registrant (owner in the .eth registrar) and controller (owner in the ENS registry), and with the NameWrapper you'll also have the owner in the NameWrapper and the controller of that name will be the NameWrapper itself.

There would have to some quite complicated logic in the `addr()` function to decide which owner to set the record to, increasing the gas for any on-chain resolutions of addresses. I'm not sure it's worth complicating this function for the gas saved.
