### ISSUE TITLE
`_consumeCommitment` in `ETHRegistrarController` need logic improvement

### ISSUE THREAD

**Issue by Muggle-Du** [ensdomains/ens-contracts#120]
```solidity
function _consumeCommitment(
        string memory name,
        uint256 duration,
        bytes32 commitment
    ) internal {
        // Require a valid commitment (is old enough and is committed)
        require(
            commitments[commitment] + minCommitmentAge <= block.timestamp,
            "ETHRegistrarController: Commitment is not valid"
        );

        // If the commitment is too old, or the name is registered, stop
        require(
            commitments[commitment] + maxCommitmentAge > block.timestamp,
            "ETHRegistrarController: Commitment has expired"
        );
.....
```
Apparently, the first require assertion can not check whether the commitment is `committed` or not because the solidity map ping supposes that every `key` of the mapping exists with the default zero value.
Luckily, the `maxCommitmentAge` in the second require assertion is small enough so that if a commitment is not `committed` it will always throw the error.
If other projects forked ens and initialized `maxCommitmentAge` with a very big value, then the `_consumeCommitment` validation is escaped.

**Comment by Arachnid** [comment]
A nonexistent commitment is the same as one that was made on 1/1/1970; the first check correctly verifies a commitment was made at least `minCommitmentAge` ago, and the second verifies it is no older than the `maxCommitmentAge`. A large `maxCommitmentAge` will not affect this.

**Comment by Muggle-Du** [comment]
No, if the commitment is not committed, `commitments[commitment] + minCommitmentAge == minCommitmentAge <= block.timestamp`, and `commitments[commitment] + maxCommitmentAge ==  maxCommitmentAge ?< block.timestamp`
so a very large `maxCommitmentAge` could make this check not work.

**Comment by Arachnid** [comment]
You're right; this seems unlikely, but harmless enough to check for in the constructor.
