### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by frangio** [ensdomains/ens-contracts#192]
This package depends on `@ensdomains/ens-buffer` which seems to accidentally depend on `@nomiclabs/hardhat-truffle5`: this should be a dev dependency but is installed as a normal dependency. As a result, a huge number of dependencies gets installed, totalling 200MB on disk.

I opened https://github.com/ensdomains/buffer/issues/21 but I'm raising this here because this package is affected and it should be fixed asap.

**Comment by v1rtl** [comment]
this issue is fixed in the latest version of ens-contracts
