### ISSUE TITLE
How to get the sender's ENS Name from the TextChanged event log?

### ISSUE THREAD

**Issue by brucexc** [ensdomains/ens-contracts#242]
After cleaning the ENS TextChanged event log, I found that it is impossible to determine which ENS this Text belongs to based on the log.

Is there any solution to this problem?

Related event log link: https://etherscan.io/tx/0x5551e94d827a52eaf4a2da30c60fd5fecd2890fa95ae922fe5ebebe96855113c#eventlog

**Comment by Arachnid** [comment]
The first parameter is 'node', which is the namehash of the name being affected. You can compute this from a known name, or look it up in the subgraph or another preimage DB. Bear in mind that it's possible for a name with no known preimage to exist.
