### ISSUE TITLE
01091423777k@gmail.com

### ISSUE THREAD

**Issue by 124maa** [ensdomains/ens-contracts#316]
![coinbase-snapshot-4997187731393639678.jpg](https://github.com/ensdomains/ens-contracts/assets/139474901/3ab8b570-5ca2-4d6e-826b-11ca411fbdf8)

**Comment by Dogblade** [comment]
![Screenshot_20240705-141041](https://github.com/ensdomains/ens-contracts/assets/151909075/5c1708c9-4a8a-41f7-8728-85c2f5b71640)

**Comment by Dogblade** [comment]
![Screenshot_20240705-125252](https://github.com/ensdomains/ens-contracts/assets/151909075/7eccfa46-0653-4185-a1dc-6a25e66598ac)
Dog

**Comment by Dogblade** [comment]
11967621801 muito contrato já estão liberados
