### ISSUE TITLE
Why use ERC-1155 instead of ERC-721 for Name Wrapper?

### ISSUE THREAD

**Issue by 0xanders** [ensdomains/ens-contracts#92]
There is only one (not many)  token for  each token id in Name Wrapper contract, why use ERC-1155 instead of ERC-721 for Name Wrapper? 

ERC-721 is simpler than ERC-1155, and I think using ERC-721 is enough for Name Wrapper.

**Comment by Arachnid** [comment]
ERC1155 is significantly more gas-efficient than ERC721.
